debug environment for kernel and glibc
kernelrookie/KernelDoc pull request #7
Opened 2020-08-28 09:02 UTC by Limaomao821

2020-08-28 09:16 UTC, Martins3 requested changes

2020-08-28 09:16 UTC, Martins3 commented on debug/debug_linux_kernel.md
> +1. 虚拟机内安装build-essential之类的开发工具方便
语病 ?

2020-08-28 09:16 UTC, Martins3 commented on debug/ref
> +https://www.opensourceforu.com/2011/03/kgdb-with-virtualbox-debug-live-kernel/
文件名修改成为 ref.md ?

2020-08-28 10:03 UTC, Martins3 approved these changes, later dismissed

2020-08-28 10:03 UTC, Martins3 commented on debug/debug_linux_kernel.md
> +   打开`Kernel debugging`下的`compile the kernel with debug info`选项
找不到这个选项啊，你的意思是打开 kdb 吗 ?

2020-08-28 10:03 UTC, Martins3 commented on debug/debug_linux_kernel.md
> +       ```
- 可以放一下，制作 initramfs 步骤的来源吗 ?
- ubuntu 之类的 initramfs 是这样的制作的吗 ?

2020-08-28 10:03 UTC, Martins3 commented on debug/debug_linux_kernel.md
> +*在此笔记的同目录下，我放了两份参考文件*
> 在此笔记的同目录下，我放了两份参考文件

替换为

> 在此笔记的同目录下的 ref.md 放了参考资料

2020-08-28 10:03 UTC, Martins3 commented on debug/glibc_debug_environment.md
> +## glibc调试环境的搭建
多了一个标题

2020-08-28 10:08 UTC, zhuweipu approved these changes, later dismissed

2020-08-28 11:32 UTC, xieby1 commented
编译龙芯的内核，调试glibc我也有做过笔记。😀
我Notes/xiebenyi/Kernel 和 Note/xiebenyi/Glibc

2020-08-28 11:33 UTC, Martins3 commented
> 编译龙芯的内核，调试glibc我也有做过笔记。😀
> 我Notes/xiebenyi/Kernel 和 Note/xiebenyi/Glibc

可以合并到这里来吗 ?

2020-08-28 11:40 UTC, xieby1 commented
已经在实验室的gitlab的笔记仓库里了
http://foxsen.3322.org:33336/loongsonlab/notes/tree/master/xiebenyi

2020-09-09 03:19 UTC, xieby1 approved these changes

2020-09-09 03:33 UTC, Martins3 approved these changes

2020-09-09 03:34 UTC, Martins3 approved these changes

2020-09-09 03:40 UTC, xieby1 approved these changes

2020-09-09 03:41 UTC, xieby1 approved these changes

2020-09-09 03:45 UTC, merged